# Autogenerated makefile for memcached, modified by hand by Chris Kjellqvist

LDS = scripts/ldscript.lds

OBJECTS = memcached.o hash.o jenkins_hash.o murmur3_hash.o slabs.o items.o assoc.o thread.o \
	  daemon.o stats.o util.o bipbuffer.o crawler.o itoa_ljust.o slab_automove.o init.o

OPTS_LENIENT = -I. -Iplib/ -I../rpmalloc/src -DHAVE_CONFIG_H -O2 -MD -MP -MF -Wall -std=c++17
OPTS = $(OPTS_LENIENT) -Werror
CC = clang++
LINKOPTS = -pthread -levent #add link script

all: $(OBJECTS)
	clang++ $(LINKOPTS) $(OBJECTS) librpmalloc.a -o exec

%.o: %.cc
	$(CC) -c $^ $(OPTS) -MT $@ -o $@

.PHONY : clean
clean: 
	rm -f $(OBJECTS)

